### PR TITLE
TASK2, add gripper description, Wesley, mizohana plz add this pull to your repo..

### PR DESCRIPTION
**Pull request by cretaceous-creature**
[root.pdf](https://github.com/iKrishneel/jsk_mbzirc_progress_report/files/620893/root.pdf)

### CODE REVIEW

**Comment by cretaceous-creature** [comment]
@wesleypchan @mizmizo 
check if I can merge...

**Comment by iKrishneel** [comment]
Should this be merged

**Comment by wesleypchan** [comment]
merged.
will refactor it into a separate file for better organization and push PR it later.

**Comment by wesleypchan** [comment]
I've moved the gripper section into a separate file for better organization. 
Chen. Please pull and make further changes in that file.

**Comment by iKrishneel** [comment]
I just proof read these section but unfortunately i pushed directly. I think it should not be a problem. If it is just checkout to previous commit

**Comment by cretaceous-creature** [comment]
yeah, its ok, not only me push to the master.

2016-11-30 16:35 GMT+09:00 Krishneel <notifications@github.com>:

**Pull request merged**
